version: '3.8'

services:
  db:
    image: postgres:15
    container_name: patient_registration_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: patients
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./patient-registration-backend
    container_name: patient_registration_backend
    restart: always
    command: npm run start:dev
    working_dir: /app
    volumes:
      - ./patient-registration-backend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: patients

  frontend:
    build:
      context: ./patient-registration-frontend
    container_name: patient_registration_frontend
    restart: always
    command: npm run dev -- --host 0.0.0.0 --port 5173
    working_dir: /app
    volumes:
      - ./patient-registration-frontend:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    depends_on:
      - backend

volumes:
  db_data:
